version: '3.8'
services:
  # redis-stack:
  #   image: redis
  #   networks:
  #     - my-network
  #   ports:
  #   - 6379:6379

  middleware:
    build:
      context: .
      dockerfile: Dockerfile
    # networks:
    #   - my-network
    ports:
    - 8081:8081
    - 6379:6379

# networks:
#   my-network:
#     driver: bridge
