micronaut:
  application:
    name: middleware
  server:
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins: 
            - http://localhost:5173
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'

  serializers:
    json:
      default-inclusion: ALWAYS
netty:
  default:
    allocator:
      max-order: 3
scope: prod
jackson:
  property-naming-strategy: SNAKE_CASE
  deserialization:
    fail-on-unknown-properties: true